# Funding is not set up for this project.
# Uncomment and fill in a line to show a "Sponsor" button on the repository.
#
# github: [spcaeo]
# ko_fi: your-username
# buy_me_a_coffee: your-username
# open_collective: your-project
# patreon: your-username
# liberapay: your-username
# tidelift: npm/your-package
# custom: ["https://example.com/donate"]
