#!/usr/bin/env node
/**
 * Re-measure every component's contrast, reading the REAL values out of each
 * component's stylesheet so the published numbers can never drift from the code.
 *
 *   npm run contrast                     report on every component
 *   npm run contrast folder-tabs         just one
 *   npm run contrast -- --sync           rewrite the generated tables
 *   npm run contrast -- --check          verify ratios AND tables (this is CI)
 *   npm run contrast -- --markdown       print the table and stop
 *
 * WHAT IS ENFORCED, and why it is not simply "everything >= 3":
 *
 *   Text needs 4.5:1 (WCAG 1.4.3) and that is enforced flatly.
 *
 *   A BOUNDARY needs 3:1 (WCAG 1.4.11), but it may be carried EITHER by the two
 *   fills differing OR by an edge stroke reading against both of them. That
 *   either/or matters: three genuinely dark fills cannot all sit 3:1 apart,
 *   because WCAG 2.x adds a flat 0.05 flare term to both sides of the ratio,
 *   which swamps any difference near black. A #333 panel cannot reach 3:1
 *   against a rail even if that rail is pure black — the ceiling is 1.66. A dark
 *   theme therefore carries its boundaries on a stroke, exactly as the original
 *   Windows-era controls carried them on a 3D border.
 *
 * Each component declares its own pairs in its component.json, so a new
 * component needs no change to this file.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { hex, loadCss, readVars, evaluate } from "./lib/contrast-core.mjs";
import { selected } from "./lib/components.mjs";

const argv = process.argv.slice(2);
const has = (f) => argv.includes(f);
const components = selected(argv);

if (!components.length) {
  console.log("No components found under components/.");
  process.exit(0);
}

const START = "<!-- CONTRAST:START -->";
const END = "<!-- CONTRAST:END -->";

/** Everything measured for one component, plus its resolved colours. */
function measure(component) {
  const spec = component.contrast;
  const css = loadCss(join(component.dir, component.css));
  const themes = {};
  for (const [theme, selector] of Object.entries(spec.themes)) {
    themes[theme] = readVars(css, selector, spec.prefix);
  }
  return { component, spec, themes, results: evaluate(themes, spec) };
}

/** The table the component README and its docs page both show. */
function markdown({ results }) {
  const themeNames = Object.keys(results);
  const usesEdge = Object.values(results)
    .flat()
    .some((r) => r.note.includes("by edge"));
  const labels = results[themeNames[0]].map((r) => r.label);
  const cell = (r) => (r.boundary ? r.note : `**${r.note}**`);
  return [
    "<!-- Generated by `npm run contrast -- --sync`. Do not edit by hand. -->",
    "",
    `| | ${themeNames.join(" | ")} | needs |`,
    `|---|${themeNames.map(() => "---").join("|")}|---|`,
    ...labels.map((label, i) => {
      const cells = themeNames.map((t) => cell(results[t][i]));
      return `| ${label} | ${cells.join(" | ")} | ${results[themeNames[0]][i].need.toFixed(1)} |`;
    }),
    "",
    // Only explain the edge route when this component actually relies on it.
    // A footnote about a mechanism the reader cannot see in the table above is
    // noise, and it makes the generated block look boilerplate rather than
    // measured.
    usesEdge
      ? "<sub>A boundary passes on **fill or edge**: three genuinely dark fills cannot sit 3:1\napart, so the stroke carries it. See the notes below.</sub>"
      : "<sub>Text needs 4.5:1 (WCAG 1.4.3); boundaries need 3:1 (WCAG 1.4.11).</sub>",
  ].join("\n");
}

/*
  Compare table rows with padding removed and dash-runs collapsed, because
  prettier turns `|---|` into `| ------- |` and pads every cell to the column
  width. Without this the formatter and this generator would each undo the other
  on every run.
*/
const normalise = (x) =>
  x
    .split("\n")
    .map((line) =>
      line.trimStart().startsWith("|")
        ? line.replace(/[ \t]/g, "").replace(/-{2,}/g, "-")
        : line.trimEnd(),
    )
    .join("\n");

function syncTables(m, check) {
  const stale = [];
  for (const rel of m.spec.tables ?? []) {
    const file = resolve(m.component.dir, rel);
    let text;
    try {
      text = readFileSync(file, "utf8");
    } catch {
      console.log(`  skipped     ${rel} (not found)`);
      continue;
    }
    const a = text.indexOf(START);
    const b = text.indexOf(END);
    if (a < 0 || b < 0) {
      console.error(`  ERROR       ${rel} is missing CONTRAST:START / CONTRAST:END markers`);
      process.exit(1);
    }
    const next = text.slice(0, a + START.length) + "\n" + markdown(m) + "\n" + text.slice(b);
    if (normalise(next) === normalise(text)) {
      console.log(`  up to date  ${rel}`);
      continue;
    }
    if (check) {
      stale.push(rel);
      console.log(`  STALE       ${rel}`);
    } else {
      writeFileSync(file, next);
      console.log(`  written     ${rel}`);
    }
  }
  return stale;
}

let failed = false;
let staleAny = [];

for (const component of components) {
  const m = measure(component);
  const anyFail = Object.values(m.results)
    .flat()
    .some((r) => !r.ok);
  if (anyFail) failed = true;

  if (has("--markdown")) {
    console.log(markdown(m));
    continue;
  }

  console.log(`\n########## ${component.name} ##########`);

  if (!has("--sync") && !has("--check")) {
    for (const [theme, vars] of Object.entries(m.themes)) {
      console.log(`\n===== ${theme.toUpperCase()} =====`);
      for (const [k, v] of Object.entries(vars)) {
        console.log(`  --${m.spec.prefix}-${k.padEnd(13)} ${hex(v)}  oklch(${v.join(" ")})`);
      }
      console.log("  " + "-".repeat(62));
      for (const r of m.results[theme]) {
        const how = r.note.replace(/\*\*/g, "");
        console.log(
          `  ${r.ok ? "PASS" : "FAIL"}  ${r.label.padEnd(28)} ${how.padStart(8)}  (needs ${r.need})`,
        );
      }
    }
  }

  if (has("--sync") || has("--check")) {
    if (anyFail) {
      console.error(`  ${component.name}: a contrast requirement FAILS — refusing to sync.`);
      continue;
    }
    staleAny.push(...syncTables(m, has("--check")));
  }
}

console.log("");
if (failed) {
  console.error("Contrast requirements NOT met. Fix the fills in the component stylesheet.\n");
  process.exit(1);
}
if (staleAny.length) {
  console.error("Contrast tables are stale. Run: npm run contrast -- --sync\n");
  process.exit(1);
}
if (!has("--markdown")) console.log("All contrast requirements met.\n");
